services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres  
    ports:
      - 5432:5432

  subjects:
    build:
      context: ./subjects
      dockerfile: dockerfile
    depends_on:
      database:
        condition: service_started
    ports:
      - 8082:8080

  students:
    build:
      context: ./students
      dockerfile: dockerfile
    depends_on:
      database:
        condition: service_started
    ports:
      - 8081:8080