services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres  
    ports:
      - 5432:5432
      
  students:
    depends_on:
        commons:
          condition: service_started
    build:
      context: ./students
      dockerfile: dockerfile
      tags: ["students"]
    ports:
      - 8081:8081

  subjects:
    depends_on:
        commons:
          condition: service_started
    build:
      context: ./subjects
      dockerfile: dockerfile
      tags: ["subjects"]
    ports:
      - 8082:8082