services:
  commons:
    build:
      context: ./commons
      dockerfile: dockerfile
    ports:
      - 8080:8080

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres  
    ports:
      - 5432:5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  subjects:
    build:
      context: ./subjects
      dockerfile: dockerfile
    depends_on:
      database:
        condition: service_started
    ports:
      - 8082:8082

  students:
    build:
      context: ./students
      dockerfile: dockerfile
    depends_on:
      database:
        condition: service_started
    ports:
      - 8081:8081